name: Feature Request
labels: [enhancement]
description: Do you want something changed or implemented?
body:
  - type: dropdown
    id: scripts
    attributes:
      label: Script
      multiple: false
      options:
        - "`clipshot.lua`"
        - "`discord.lua`"
        - "`misc.lua`"
        - "`open-dialog/kdialog.lua`"
        - "`open-dialog/powershell.lua`"
        - "`open-dialog/zenity.lua`"
    validations: {required: true}
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Provide a detailed description of the
        change or addition you are proposing.
    validations: {required: true}
  - type: textarea
    id: suggestion
    attributes:
      label: Possible Implementation
      description: >-
        Can you suggest an idea for implementing the feature?
    validations: {required: false}
  - type: textarea
    id: context
    attributes:
      label: Context
      description: >-
        Why is this change or addition important to you?
        How would you use it, and how can it benefit other users?
    validations: {required: false}
  - type: checkboxes
    id: operating-system
    attributes:
      label: Operating System(s)
      options:
        - label: Windows
        - label: Linux
        - label: macOS
