name: Check scripts with luacheck

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua:
          - ver: 5.1.5
            std: lua51
          - ver: 5.2.4
            std: lua52c
          - ver: luajit-2.0.5
            std: luajit
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: leafo/gh-actions-lua@v8.0.0
        name: Install lua - ${{matrix.lua.ver}}
        with:
          luaVersion: ${{matrix.lua.ver}}
      - uses: leafo/gh-actions-luarocks@v4.0.0
        name: Install luarocks
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Lint with luacheck
        run: luacheck --std ${{matrix.lua.std}} .
