name: Check scripts with luacheck

on:
  push:
    branches: [master]
    paths-ignore:
      - _config.yml
      - LICENSE.txt
      - README.md
      - open-dialog/README.md
  pull_request:
    paths-ignore:
      - _config.yml
      - LICENSE.txt
      - README.md
      - open-dialog/README.md

jobs:
  luacheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua:
          - ver: 5.1.5
            std: lua51
          - ver: 5.2.4
            std: lua52c
          - ver: luajit-2.0.5
            std: luajit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install lua [${{matrix.lua.ver}}]
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{matrix.lua.ver}}
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v5
        with:
          luarocksVersion: 3.12.2
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Lint with luacheck
        run: luacheck --std ${{matrix.lua.std}} .
