name: Check scripts with luacheck

on:
  push:
    branches: [master]
    paths: ["**/*.lua"]
  pull_request:
    paths: ["**/*.lua"]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua:
          - ver: 5.1.5
            std: lua51
          - ver: 5.2.4
            std: lua52c
          - ver: luajit-2.0.5
            std: luajit
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: leafo/gh-actions-lua@ecdb13962d7d7274594480620bb6075504122bfe
        name: Install lua [${{matrix.lua.ver}}]
        with:
          luaVersion: ${{matrix.lua.ver}}
      - uses: leafo/gh-actions-luarocks@4dcae7fc5aff45e847b32f62b60a13167e912395
        name: Install luarocks
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Lint with luacheck
        run: luacheck --std ${{matrix.lua.std}} .
